/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { IUniswapV2Pair } from "./IUniswapV2Pair";
export type { IUniswapV3Pool } from "./IUniswapV3Pool";
export type { IWETH } from "./IWETH";
export type { MyArb } from "./MyArb";
